---
title: "CalculatingRichness"
author: "PetraGuy"
date: "7 February 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
rm(list = ls())
cat("\014")
library(dplyr)
library(ggplot2)
```

```{r}
#This analysis will take the vegetation data and compute species richness by nest,plot and site. These values will be saved to csv files which can be added to the Nest and Plot level data sets.
#wood_rich from maps.R required

```

```{r}
#Input all the ground flora data
Data = read.csv("../Data/GroundCover.csv")
Data_Yr2 = Data%>%filter(Yr_2 == 2)#%>%select(SITE,PLOT,NEST,COV,Amalgams)
colnames(Data_Yr2) = c("SITE", "PLOT","NEST","Cover","BRC_number","Year")
veg_codes = read.csv("../Data/vegetation_codes.csv")
# the  bryophytes, lichen etc have already been removed from these. 

colnames(veg_codes) = c("Species", "BRC_number")
Data_Yr2_veg = Data_Yr2%>% inner_join(veg_codes)

# returns the species richness for each site/plot/nest as a list of data frames
# richness[[3]] will give plot by nest data frame of richness
# NAs are not counted, these occur for sapling counts which need to be added in to the plot richness.

nest_richness = function(data){
  site_list = list()
  #browser()
    for (i in 1:103){
    sitedata = data%>%filter(SITE == i)
    plot_nest_df = data.frame()
    for (j in 1:16){
      plotdata = sitedata%>%filter(PLOT == j)
      tmp = vector()
       for (k in 1:5){
        nestdata = plotdata%>%filter(NEST ==k)
        tmp = c(tmp, nrow(nestdata))
        }
      plot_nest_df = rbind(plot_nest_df, tmp)
      colnames(plot_nest_df) = c("nest1","nest2","nest3","nest4","nest5")
    }
   site_list[[i]]= plot_nest_df
  }
return(site_list)   
}
spec_rich = nest_richness(Data_Yr2_veg)
#Since nest level data is only modelled as species~area - no other vars, spec_rich list is all thats 
#needed. This data will be analysed from this document, a csv is not needed because it is not being added #to another file.
#spec_rich is list, spec_rich[[1]] returns list of richnesses for plot 1-16, nest 1-5 in site 1
# this does not include saplings unless recored - i.e. they will be little baby plants.

# now need to include the NAs and combine them into a plot richness
plot_richness = function(data){
  site_matrix = matrix(nrow = 103, ncol = 16)
  #browser()
  for (i in 1:103){
    sitedata = data%>%filter(SITE == i)
    plot_nest_df = data.frame()
    for (j in 1:16){
      plotdata = sitedata%>%filter(PLOT == j)
      site_matrix[i,j] = length(unique(plotdata$BRC_number))
      # for the seedlings there is sometimes record in specified plot, and NA record, therefore have 
      #used unique to capture those that are NAs, but not double count when same species listed in a nest
    }
  }
  return(site_matrix)
}
plot_rich = plot_richness(Data_Yr2_veg)

#plot_rich[i,j] returns richness for site i plot j. May not equate to sum of nest richness because saplings are included.

#Missing plots come up as 0s - but note, some "missing" plots do have vegetation entries. Handle within each #woodland modelled??
write.csv(plot_rich,"../Data/plot_rich.csv")

#species richness per nest is not saved to csv because its a list.
#use spec_rich[[1]] for nest richness of all plots of site 1
```

```{r}
# just calculates richness found in each wood, no extrapolation.
#d[i] is richness of wood i
basic_richness = function(data){
  d = rep(0,103)
 for (i in 1:103){
   site = data%>%filter(SITE==i)
   d[i]  = length(unique(site$BRC_number))
 }
  return(d)
} 
d = basic_richness(Data_Yr2_veg)

```

```{r}
##Plot richnesses. cum_rich_all[[1]] will give the cumulative richness for site 1, for all 16 plots.
##need spec_rich calculated above

cum_rich_all = list()
for ( i in 1:103){
  #browser()
  site = spec_rich[[i]]
  site = as.data.frame(site)
  cum_rich_site = data.frame()
   for (j in 1:16) {
    plot = site[j,]
    r = 0
    cumrich = rep(0,5)
    for (n in 1:5){
      r = r + plot[[n]]
      cumrich[n] = r
    }
    cum_rich_site = rbind(cum_rich_site, cumrich)
   }
  colnames(cum_rich_site) = c("nest1","nest2","nest3","nest4","nest5")
  cum_rich_all[[i]] = cum_rich_site
}
#cum_rich_all is list of cumulative richness for each plot/site. cum_rich_all[[1]] gives cumulative
#richness for all plots in site 1 for nest 1 - 5
```


```{r}
#some stats
#wood_rich calcualted in maps.R - it binds the richness to location vars
max_wood = wood_rich%>%filter(Site==match(max(d),d))
min_wood = wood_rich%>%filter(Site==match(min(d),d))
#wont work with 0s
plot_rich[plot_rich == 0] = NA

mins = apply(plot_rich,1,min,na.rm=TRUE)
maxs = apply(plot_rich,1,max,na.rm=TRUE)
ranges = maxs - mins
max_range= max(ranges)
min_range = min(ranges)
max_range_wood = wood_rich%>%filter(Site==match(max(ranges),ranges))
min_range_wood = wood_rich%>%filter(Site==match(min(ranges),ranges))
stats = rbind(max_wood,min_wood, max_range_wood, min_range_wood)
values = c(max(d),min(d),max_range,min_range)
n = colnames(stats)
n = c(n[-7],"values")
colnames(stats) = n
rownames(stats) = c("max richness","min richness","max range","min range")

```

```{r}
#Look at top and bottom quartiles?
u_woods = wood_rich%>%filter(d>100)
l_woods = wood_rich%>%filter(d<60)
good_bad = rbind(u_woods,l_woods)

```

