---
title: "Exploration of richness at nest level"
author: "PetraGuy"
date: "1 March 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
plots = c("plot1","plot2","plot3","plot4","plot5","plot6","plot7",
          "plot8","plot9","plot10","plot11","plot12","plot13","plot14","plot15","plot16")
area = c("4","25","50","100","200") 
areas = sort(as.numeric(rep(area,16)), decreasing = FALSE)


plot_site = function(sitevector){
 #browser()
  for (i in 1:length(sitevector)){
    site = sitevector[i]
    cf_site = cum_rich_all[[site]]
    cf_site$plot = plots
    melted_cf = melt(cf_site)
    melted_cf$area = areas
    siteno  = paste("Site",site)
    p = ggplot(melted_cf)+
      geom_point(aes(x = area, y = value), colour = "black")+
      labs(title = siteno)+
      theme(plot.title = element_text(size = 10))
     plot_list[[i]] = p
     
      
  }
  return(plot_list)
}
```


```{r}

up_woods =  wood_rich%>%filter(d>115)
site_to_plot = up_woods$Site
plot_list =list()

plots_all = plot_site(site_to_plot)

grid.arrange(plots_all[[1]], plots_all[[2]], plots_all[[3]],
             plots_all[[4]], plots_all[[5]], plots_all[[6]],
             plots_all[[7]],plots_all[[8]], ncol = 2)
```

```{r, messgase = FALSE}
lo_woods = wood_rich%>%filter(d<45)
site_to_plot = lo_woods$Site
plot_list =list()
plots_all = plot_site(site_to_plot)
grid.arrange(plots_all[[1]], plots_all[[2]], plots_all[[3]],
             plots_all[[4]], plots_all[[5]], plots_all[[6]],
             plots_all[[7]],plots_all[[8]], ncol = 2)
```


